title: Roshan’s AWS Portfolio
description: My showcase of cloud-native architecture, IaC, and the lessons learned.
baseurl: ""          # leave empty for root GitHub Pages
url: "https://roshan-aws-personal.github.io"

# Collections (optional, for chapters)
collections:
  chapters:
    output: true
    permalink: /:collection/:name/